### ISSUE TITLE
public struct cudaDeviceProp in driver_types.cs does not match NVidia documentation

### ISSUE THREAD

**Issue by gardnerbp** [DNRY/CSCuda#21]
Especially problematic is the omission of uuid, which causes all fields to shift out of alignment with what CUDA returns. To see correct structure for CUDA 11.7, see https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g1bf9d625a931d657e08db2b4391170f0

**Comment by yhbyhb** [comment]
Thanks for reporting issue.
Fixed cudaDeviceProp implementation as written in document.
Please use the latest source or nuget package.
